services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: curso/php8.3.10-fpm-alpine3
#        ports:
#            - '${VITE_PORT:-5173}:5173'
        volumes:
            - ./:/var/www/html
        restart: unless-stopped
    web:
        depends_on:
            - php
        image: nginx:stable-alpine
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
